osx_image: xcode7.1
os:
- osx
language: node_js
node_js:
- 6.1.0
script: npm run dist
cache:
  directories:
    - node_modules
    - $HOME/.electron
    - "test/fixtures/app-executable-deps/app/node_modules"
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: dist/mac/Perlotto-*.dmg
  on:
    tags: true
    repo: can3p/perlotto
